[package]
name = "solver"
version = "0.1.0"
authors = ["John BÃ¤ckstrand <sopues@gmail.com>"]

[dependencies]
csv = "1"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false